// Generated by gencpp from file srv/communicateResponse.msg
// DO NOT EDIT!


#ifndef SRV_MESSAGE_COMMUNICATERESPONSE_H
#define SRV_MESSAGE_COMMUNICATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv
{
template <class ContainerAllocator>
struct communicateResponse_
{
  typedef communicateResponse_<ContainerAllocator> Type;

  communicateResponse_()
    : result(0)  {
    }
  communicateResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::srv::communicateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv::communicateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct communicateResponse_

typedef ::srv::communicateResponse_<std::allocator<void> > communicateResponse;

typedef boost::shared_ptr< ::srv::communicateResponse > communicateResponsePtr;
typedef boost::shared_ptr< ::srv::communicateResponse const> communicateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv::communicateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv::communicateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv::communicateResponse_<ContainerAllocator1> & lhs, const ::srv::communicateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv::communicateResponse_<ContainerAllocator1> & lhs, const ::srv::communicateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv::communicateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv::communicateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::communicateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::communicateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::communicateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::communicateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv::communicateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::srv::communicateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv::communicateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv/communicateResponse";
  }

  static const char* value(const ::srv::communicateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv::communicateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 服务器响应发送的数据\n"
"int32 result\n"
;
  }

  static const char* value(const ::srv::communicateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv::communicateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct communicateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv::communicateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv::communicateResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_MESSAGE_COMMUNICATERESPONSE_H
